package com.example.architectureplatform.report.dto.request;

import com.example.architectureplatform.report.enums.ReportType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record CreateReportRequest(
        @NotBlank(message = "Report name is required")
        @Size(max = 255, message = "Report name must not exceed 255 characters")
        String name,

        @Size(max = 5000, message = "Description must not exceed 5000 characters")
        String description,

        @NotNull(message = "Report type is required")
        ReportType reportType,

        @Size(max = 255, message = "Generated by must not exceed 255 characters")
        String generatedBy,

        LocalDate reportPeriodStart,

        LocalDate reportPeriodEnd,

        LocalDateTime generatedAt
) {
}