import { useEffect, useState } from 'react';
import { reportsAPI } from '../../api/services';

const REPORT_TYPES = ['FINANCIAL', 'PROJECT', 'EXPENSE', 'INVOICE', 'PAYMENT', 'CONSULTATION', 'TEAM', 'CUSTOM'];

const emptyForm = {
    name: '', description: '', reportType: 'FINANCIAL',
    generatedBy: '', reportPeriodStart: '', reportPeriodEnd: '',
};

function Modal({ title, onClose, children }) {
    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h3>{title}</h3>
                    <button className="modal-close" onClick={onClose}>✕</button>
                </div>
                <div className="modal-body">{children}</div>
            </div>
        </div>
    );
}

function ReportForm({ initial, onSubmit, onClose, loading }) {
    const [form, setForm] = useState(initial || emptyForm);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setForm(f => ({ ...f, [name]: value }));
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        const payload = { ...form };
        if (!payload.description) delete payload.description;
        if (!payload.generatedBy) delete payload.generatedBy;
        if (!payload.reportPeriodStart) delete payload.reportPeriodStart;
        if (!payload.reportPeriodEnd) delete payload.reportPeriodEnd;
        onSubmit(payload);
    };

    return (
        <form onSubmit={handleSubmit} className="project-form">
            <div className="form-section">
                <div className="form-section-title">Report Info</div>
                <div className="form-row">
                    <div className="form-field">
                        <label>Report Name *</label>
                        <input name="name" value={form.name} onChange={handleChange}
                               placeholder="Q1 Financial Summary" required />
                    </div>
                    <div className="form-field">
                        <label>Report Type *</label>
                        <select name="reportType" value={form.reportType} onChange={handleChange} required>
                            {REPORT_TYPES.map(t => <option key={t} value={t}>{t.replace(/_/g, ' ')}</option>)}
                        </select>
                    </div>
                </div>
                <div className="form-field">
                    <label>Generated By</label>
                    <input name="generatedBy" value={form.generatedBy} onChange={handleChange}
                           placeholder="System or person name" />
                </div>
                <div className="form-field">
                    <label>Description</label>
                    <textarea name="description" value={form.description} onChange={handleChange}
                              rows={3} placeholder="Report description..." />
                </div>
            </div>

            <div className="form-section">
                <div className="form-section-title">Report Period</div>
                <div className="form-row">
                    <div className="form-field">
                        <label>Period Start</label>
                        <input name="reportPeriodStart" type="date" value={form.reportPeriodStart} onChange={handleChange} />
                    </div>
                    <div className="form-field">
                        <label>Period End</label>
                        <input name="reportPeriodEnd" type="date" value={form.reportPeriodEnd} onChange={handleChange} />
                    </div>
                </div>
            </div>

            <div className="form-actions">
                <button type="button" className="btn-ghost" onClick={onClose}>Cancel</button>
                <button type="submit" className="btn-primary" disabled={loading}>
                    {loading ? 'Saving...' : 'Save Report →'}
                </button>
            </div>
        </form>
    );
}

function DetailView({ report }) {
    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            <div className="detail-grid">
                <div className="detail-item">
                    <span className="detail-label">Name</span>
                    <span className="detail-value">{report.name}</span>
                </div>
                <div className="detail-item">
                    <span className="detail-label">Type</span>
                    <span className="type-badge">{report.reportType?.replace(/_/g, ' ')}</span>
                </div>
                <div className="detail-item">
                    <span className="detail-label">Generated By</span>
                    <span className="detail-value">{report.generatedBy || '—'}</span>
                </div>
                <div className="detail-item">
                    <span className="detail-label">Generated At</span>
                    <span className="detail-value">
            {report.generatedAt ? new Date(report.generatedAt).toLocaleString() : '—'}
          </span>
                </div>
                <div className="detail-item">
                    <span className="detail-label">Period Start</span>
                    <span className="detail-value">
            {report.reportPeriodStart ? new Date(report.reportPeriodStart).toLocaleDateString() : '—'}
          </span>
                </div>
                <div className="detail-item">
                    <span className="detail-label">Period End</span>
                    <span className="detail-value">
            {report.reportPeriodEnd ? new Date(report.reportPeriodEnd).toLocaleDateString() : '—'}
          </span>
                </div>
            </div>
            {report.description && (
                <div className="detail-item">
                    <span className="detail-label">Description</span>
                    <p className="detail-text">{report.description}</p>
                </div>
            )}
            <div className="detail-item">
                <span className="detail-label">Created</span>
                <span className="detail-value">
          {report.createdAt ? new Date(report.createdAt).toLocaleString() : '—'}
        </span>
            </div>
        </div>
    );
}

export default function ReportsPage() {
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState('');
    const [search, setSearch] = useState('');
    const [filterType, setFilterType] = useState('');
    const [showCreate, setShowCreate] = useState(false);
    const [editReport, setEditReport] = useState(null);
    const [viewReport, setViewReport] = useState(null);

    const fetchReports = async () => {
        setLoading(true);
        try {
            const res = await reportsAPI.getAll();
            setReports(res.data?.data || []);
        } catch (e) {
            setError('Failed to load reports');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { fetchReports(); }, []);

    const handleCreate = async (form) => {
        setSaving(true);
        try {
            await reportsAPI.create(form);
            setShowCreate(false);
            fetchReports();
        } catch (e) {
            setError(e.response?.data?.message || 'Failed to create report');
        } finally {
            setSaving(false);
        }
    };

    const handleUpdate = async (form) => {
        setSaving(true);
        try {
            await reportsAPI.update(editReport.id, form);
            setEditReport(null);
            fetchReports();
        } catch (e) {
            setError(e.response?.data?.message || 'Failed to update report');
        } finally {
            setSaving(false);
        }
    };

    const handleDelete = async (id) => {
        if (!window.confirm('Are you sure you want to delete this report?')) return;
        try {
            await reportsAPI.delete(id);
            fetchReports();
        } catch (e) {
            setError('Failed to delete report');
        }
    };

    const filtered = reports.filter(r => {
        const matchSearch = !search ||
            r.name?.toLowerCase().includes(search.toLowerCase()) ||
            r.generatedBy?.toLowerCase().includes(search.toLowerCase());
        const matchType = !filterType || r.reportType === filterType;
        return matchSearch && matchType;
    });

    return (
        <div className="page">
            <div className="page-header">
                <div>
                    <h1 className="page-title">Reports</h1>
                    <p className="page-subtitle">{reports.length} total reports</p>
                </div>
                <button className="btn-primary" onClick={() => setShowCreate(true)}>
                    + New Report
                </button>
            </div>

            {error && (
                <div className="page-error" onClick={() => setError('')}>
                    ⚠ {error} <span style={{ opacity: 0.5 }}>✕</span>
                </div>
            )}

            <div className="page-filters">
                <input
                    className="filter-search"
                    placeholder="Search by name or generated by..."
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                />
                <select className="filter-select" value={filterType} onChange={e => setFilterType(e.target.value)}>
                    <option value="">All Types</option>
                    {REPORT_TYPES.map(t => <option key={t} value={t}>{t.replace(/_/g, ' ')}</option>)}
                </select>
            </div>

            <div className="page-table-card">
                {loading ? (
                    <div className="table-loading">
                        {Array.from({ length: 5 }).map((_, i) => <div key={i} className="skeleton-row" />)}
                    </div>
                ) : filtered.length === 0 ? (
                    <div className="table-empty-state">
                        <div className="empty-icon">▣</div>
                        <h3>No reports found</h3>
                        <p>{search || filterType ? 'Try adjusting your filters' : 'Create your first report'}</p>
                        {!search && !filterType && (
                            <button className="btn-primary" onClick={() => setShowCreate(true)}>+ New Report</button>
                        )}
                    </div>
                ) : (
                    <table className="data-table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Generated By</th>
                            <th>Period</th>
                            <th>Generated At</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {filtered.map(r => (
                            <tr key={r.id}>
                                <td>
                                    <div className="cell-title">{r.name}</div>
                                    {r.description && (
                                        <div className="cell-sub" style={{
                                            maxWidth: '260px', overflow: 'hidden',
                                            textOverflow: 'ellipsis', whiteSpace: 'nowrap'
                                        }}>
                                            {r.description}
                                        </div>
                                    )}
                                </td>
                                <td><span className="type-badge">{r.reportType?.replace(/_/g, ' ')}</span></td>
                                <td>{r.generatedBy || <span style={{ color: 'var(--text-muted)' }}>—</span>}</td>
                                <td style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
                                    {r.reportPeriodStart && r.reportPeriodEnd
                                        ? `${new Date(r.reportPeriodStart).toLocaleDateString()} – ${new Date(r.reportPeriodEnd).toLocaleDateString()}`
                                        : r.reportPeriodStart
                                            ? `From ${new Date(r.reportPeriodStart).toLocaleDateString()}`
                                            : '—'
                                    }
                                </td>
                                <td style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
                                    {r.generatedAt ? new Date(r.generatedAt).toLocaleDateString() : '—'}
                                </td>
                                <td>
                                    <div className="action-btns">
                                        <button className="action-btn" onClick={() => setViewReport(r)} title="View">◉</button>
                                        <button className="action-btn" onClick={() => setEditReport(r)} title="Edit">✎</button>
                                        <button className="action-btn action-btn-danger" onClick={() => handleDelete(r.id)} title="Delete">✕</button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                        </tbody>
                    </table>
                )}
            </div>

            {showCreate && (
                <Modal title="New Report" onClose={() => setShowCreate(false)}>
                    <ReportForm onSubmit={handleCreate} onClose={() => setShowCreate(false)} loading={saving} />
                </Modal>
            )}

            {editReport && (
                <Modal title="Edit Report" onClose={() => setEditReport(null)}>
                    <ReportForm
                        initial={{
                            ...editReport,
                            reportPeriodStart: editReport.reportPeriodStart || '',
                            reportPeriodEnd: editReport.reportPeriodEnd || '',
                        }}
                        onSubmit={handleUpdate}
                        onClose={() => setEditReport(null)}
                        loading={saving}
                    />
                </Modal>
            )}

            {viewReport && (
                <Modal title="Report Details" onClose={() => setViewReport(null)}>
                    <DetailView report={viewReport} />
                </Modal>
            )}
        </div>
    );
}